apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: inno
type: Opaque
stringData:
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

  GATEWAY_API_KEY: "gateway-secret-key"
  USER_SERVICE_API_KEY: "user-service-key-321"
  ORDER_SERVICE_API_KEY: "order-service-key-123"

  USER_POSTGRES_USER: "postgres"
  USER_POSTGRES_PASSWORD: "postgres"
  USER_POSTGRES_DB: "user_db"

  AUTH_POSTGRES_USER: "postgres"
  AUTH_POSTGRES_PASSWORD: "postgres"
  AUTH_POSTGRES_DB: "auth_db"

  ORDER_POSTGRES_USER: "postgres"
  ORDER_POSTGRES_PASSWORD: "postgres"
  ORDER_POSTGRES_DB: "order_db"

  MONGO_USER: "mongo"
  MONGO_PASSWORD: "mongo"
  MONGODB_DATABASE: "payment_db"
  MONGODB_URI: "mongodb://mongo:mongo@mongodb:27017/payment_db?authSource=admin"

  CARD_ENCRYPTION_KEY: "17kqIAFU7411I84BYLfsif12Ir42uewb"