apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: inno
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: goylikdmitry/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GATEWAY_API_KEY
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: USER_SERVICE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AUTH_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PAYMENT_SERVICE_URL
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"