apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: inno
data:
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-postgres:5432/auth_db"
  SPRING_LIQUIBASE_CHANGELOG: "classpath:db/changelog/db.changelog-master.yaml"
  JWT_ACCESS_TOKEN_EXPIRATION_MS: "900000"
  JWT_REFRESH_TOKEN_EXPIRATION_MS: "604800000"
